server:
  port: 8081

spring:
  application:
    name: SmartShop

  datasource:
    driver-class-name: org.postgresql.Driver
    username: aliyara29
    password: Yara2001
    url: jdbc:postgresql://localhost:5432/smartshop_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: app.log
  level:
    root: INFO
    com.aliyara.smartshop: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

vat:
  value: 20